# Generated by Django 4.1.2 on 2022-12-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_teacher_other_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='role',
            new_name='position',
        ),
    ]
