# Generated by Django 4.1.2 on 2022-12-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_rename_role_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Other_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Conventional_Grade', models.CharField(max_length=50)),
                ('Conventional_Arm', models.CharField(max_length=50)),
                ('Islamiya_Grade', models.CharField(max_length=50)),
                ('Islamiya_Arm', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Genotype', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('State_of_Origin', models.CharField(max_length=50)),
                ('State_of_Residence', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=50)),
                ('Local_Language', models.CharField(max_length=100)),
                ('NIN', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(max_length=1000)),
                ('Dad_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Dad_First_Name', models.CharField(max_length=50)),
                ('Dad_Surname', models.CharField(max_length=50)),
                ('Dad_Other_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Dad_Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Dad_Home_Address', models.CharField(max_length=1000)),
                ('Dad_Work_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Dad_Phone_home', models.CharField(max_length=50)),
                ('Dad_Phone_work', models.CharField(blank=True, max_length=50, null=True)),
                ('Dad_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Mom_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Mom_First_Name', models.CharField(max_length=50)),
                ('Mom_Surname', models.CharField(max_length=50)),
                ('Mom_Other_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mom_Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Mom_Home_Address', models.CharField(max_length=1000)),
                ('Mom_Work_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Mom_Phone_home', models.CharField(max_length=50)),
                ('Mom_Phone_work', models.CharField(blank=True, max_length=50, null=True)),
                ('Mom_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Sickness', models.CharField(blank=True, max_length=500, null=True)),
                ('Disabilities', models.CharField(blank=True, max_length=500, null=True)),
                ('Allergies', models.CharField(blank=True, max_length=500, null=True)),
                ('Symptoms', models.CharField(blank=True, max_length=500, null=True)),
                ('Registered_Hospoital', models.CharField(blank=True, max_length=200, null=True)),
                ('Card_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Hospital_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Hospital_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_Contact', models.CharField(max_length=50)),
                ('Medical_Contact_Address', models.CharField(max_length=1000)),
                ('Medical_Contact_Relationship', models.CharField(max_length=50)),
                ('Medical_Contact_Phone', models.CharField(max_length=50)),
                ('Medical_Emergency_Hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('Medical_Emergency_Hospital_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Birth_Cert', models.FileField(upload_to='pupil_attachments')),
                ('Indigene_Cert', models.FileField(upload_to='pupil_attachments')),
                ('Medical_Cert', models.FileField(upload_to='pupil_attachments')),
                ('National_id', models.FileField(upload_to='pupil_attachments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
