# Generated by Django 4.1.2 on 2022-12-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_pupil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pupil',
            old_name='Other_Name',
            new_name='other_name',
        ),
        migrations.RenameField(
            model_name='pupil',
            old_name='Surname',
            new_name='surname',
        ),
    ]
