# Generated by Django 4.1.2 on 2022-12-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_pupil_adm_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='ADM_No',
        ),
    ]
