# Generated by Django 4.1.2 on 2022-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_pupil_adm_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='ADM_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
