# Generated by Django 4.1.2 on 2022-12-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
