# Generated by Django 4.1.2 on 2022-12-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='Conventional_Arm',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='Conventional_Grade',
            field=models.CharField(choices=[('nursery1', 'nursery 1'), ('nursery2', 'nursery 2'), ('grade1', 'grade 1'), ('grade2', 'grade 2'), ('grade3', 'grade 3'), ('grade4', 'grade 4'), ('grade5', 'grade 5'), ('grade6', 'grade 6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='Islamiya_Arm',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='Islamiya_Grade',
            field=models.CharField(choices=[('nursery1', 'nursery 1'), ('nursery2', 'nursery 2'), ('grade1', 'grade 1'), ('grade2', 'grade 2'), ('grade3', 'grade 3'), ('grade4', 'grade 4'), ('grade5', 'grade 5'), ('grade6', 'grade 6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Arm',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Grade',
            field=models.CharField(blank=True, choices=[('nursery1', 'nursery 1'), ('nursery2', 'nursery 2'), ('grade1', 'grade 1'), ('grade2', 'grade 2'), ('grade3', 'grade 3'), ('grade4', 'grade 4'), ('grade5', 'grade 5'), ('grade6', 'grade 6')], max_length=50, null=True),
        ),
    ]
