# Generated by Django 4.1.2 on 2022-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_pupil_conventional_arm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Arm',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Grade',
            field=models.CharField(blank=True, choices=[('nursery1', 'nursery 1'), ('nursery2', 'nursery 2'), ('1', 'grade 1'), ('2', 'grade 2'), ('3', 'grade 3'), ('4', 'grade 4'), ('5', 'grade 5'), ('6', 'grade 6')], max_length=50, null=True),
        ),
    ]
