# Generated by Django 4.1.2 on 2022-12-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_pupil_conventional_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='Conventional_Grade',
            field=models.CharField(choices=[('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='Islamiya_Grade',
            field=models.CharField(choices=[('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Grade',
            field=models.CharField(blank=True, choices=[('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
    ]
