# Generated by Django 4.1.2 on 2022-12-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_pupil_conventional_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='Sickness',
            new_name='Sicknesses',
        ),
    ]
