# Generated by Django 4.1.2 on 2022-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_rename_sickness_pupil_sicknesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='passport',
            field=models.ImageField(default='images/pngs/profile.jpeg', upload_to='pupil_passports'),
        ),
    ]
