# Generated by Django 4.1.2 on 2022-12-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_pupil_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Islamiya_Grade6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Islamiya_Grade5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Islamiya_Grade4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Islamiya_Grade3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Islamiya_Grade2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Islamiya_Grade1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Conventional_Grade1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('Second_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('Third_Term_Result', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('First_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('Second_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('Third_Term_Report', models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One')),
                ('Pupil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil')),
            ],
        ),
    ]
