# Generated by Django 4.1.2 on 2022-12-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_islamiya_grade6_islamiya_grade5_islamiya_grade4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
    ]
