# Generated by Django 4.1.2 on 2022-12-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_conventional_grade6_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade1',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade2',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade3',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade4',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade5',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade6',
            name='Pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
    ]
