# Generated by Django 4.1.2 on 2022-12-31 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_alter_conventional_grade1_first_term_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventional_grade1',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade1',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade2',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade3',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade4',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade5',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='First_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Second_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Third_Term_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='conventional_grade6',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade1',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade1',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade1',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade1',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade2',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade2',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade2',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade2',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade3',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade3',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade3',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade3',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade4',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade4',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade4',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade4',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade5',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade5',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade5',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade5',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade6',
            name='First_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade6',
            name='Pupil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.pupil'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade6',
            name='Second_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
        migrations.AlterField(
            model_name='islamiya_grade6',
            name='Third_Term_Result',
            field=models.FileField(blank=True, null=True, upload_to='Islamiya_Grade_Six'),
        ),
    ]
