# Generated by Django 4.1.2 on 2022-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_alter_conventional_grade1_first_term_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventional_grade2',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='conventional_grade3',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='conventional_grade4',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='conventional_grade5',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='conventional_grade6',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade1',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade2',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade3',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade4',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade5',
            name='Pupil',
        ),
        migrations.RemoveField(
            model_name='islamiya_grade6',
            name='Pupil',
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_1_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_2_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_3_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_4_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_5_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_6_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Grade_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='First_Term_Saff_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_1_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_2_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_3_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_4_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_5_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_6_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Grade_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Second_Term_Saff_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_1_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_2_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_3_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_4_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_5_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_6_Report',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Grade_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Grade_Six'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_1_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_One'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_2_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Two'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_3_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Three'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_4_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Four'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_5_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Five'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='Third_Term_Saff_6_Result',
            field=models.FileField(blank=True, null=True, upload_to='Conventional_Saff_Six'),
        ),
        migrations.DeleteModel(
            name='Conventional_Grade1',
        ),
        migrations.DeleteModel(
            name='Conventional_Grade2',
        ),
        migrations.DeleteModel(
            name='Conventional_Grade3',
        ),
        migrations.DeleteModel(
            name='Conventional_Grade4',
        ),
        migrations.DeleteModel(
            name='Conventional_Grade5',
        ),
        migrations.DeleteModel(
            name='Conventional_Grade6',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade1',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade2',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade3',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade4',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade5',
        ),
        migrations.DeleteModel(
            name='Islamiya_Grade6',
        ),
    ]
