# Generated by Django 4.1.2 on 2023-01-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_remove_conventional_grade2_pupil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('CONVENTIONAL TEACHER', 'CONVENTIONAL TEACHER'), ('NURSERY TEACHER', 'NURSERY TEACHER'), ('ISLAMIYA TEACHER', 'ISLAMIYA TEACHER'), ('PRIMARY HEAD', 'PRIMARY HEAD'), ('NURSERY HEAD', 'NURSERY HEAD'), ('ISLAMIYA HEAD', 'ISLAMIYA HEAD'), ('CONVENTIONAL HEAD', 'CONVENTIONAL HEAD')], max_length=50),
        ),
    ]
