# Generated by Django 4.1.2 on 2022-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('surName', models.CharField(max_length=30)),
                ('otherName', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('originState', models.CharField(max_length=30)),
                ('residenceState', models.CharField(max_length=30)),
                ('address', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('maritalStatus', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('studyField', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('hireReason', models.TextField(max_length=5000)),
                ('cv', models.FileField(upload_to='docs')),
                ('letter', models.FileField(upload_to='docs')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
