# Generated by Django 4.1.2 on 2022-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Other_Name', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('State_of_Origin', models.CharField(max_length=50)),
                ('State_of_residence', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.CharField(max_length=50)),
                ('Marital_Status', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Field_of_Study', models.CharField(max_length=50)),
                ('Course_of_study', models.CharField(max_length=50)),
                ('CV', models.FileField(upload_to='docs')),
                ('Application_letter', models.FileField(upload_to='docs')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='teachingApplication',
        ),
    ]
