# Generated by Django 4.1.2 on 2022-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_delete_teachingapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Other_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
