# Generated by Django 4.1.2 on 2022-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Headline',
            field=models.CharField(max_length=1000),
        ),
    ]
