# Generated by Django 4.1.2 on 2022-12-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
