# Generated by Django 4.1.2 on 2022-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Gender',
            field=models.CharField(max_length=50),
        ),
    ]
